#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------
set -x

wclean libso granularRheologyModels
wclean libso phaseModel
wclean libso elasticModels
wclean libso interfacialModels
wclean libso kineticTheoryModels
wclean

#------------------------------------------------------------------------------
